services:
  firefly-teller-connector:
    container_name: firefly-teller-connector
    image: ghcr.io/breakthestatic/firefly-teller-connector:latest
    volumes:
      - ./data:/app/data
    ports:
      - 8080:8080
