services:
  firefly-teller-connector:
    container_name: firefly-teller-connector
    image: ghcr.io/breakthestatic/firefly-teller-connector:latest
    volumes:
      - ./data:/app/data
    ports:
      - 8080:8080
    environment:
      CRON_TIME: '0 0 * * * *'
      DAYS_TO_FETCH: 5
      TIME_ZONE: America/Los_Angeles
